# Generated by Django 2.2 on 2020-10-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokentfa',
            name='id',
        ),
        migrations.AddField(
            model_name='tokentfa',
            name='token_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token'),
            preserve_default=False,
        ),
    ]
