# Generated by Django 2.2 on 2020-09-30 08:47

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200930_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[users.validators.validate_phone_number]),
        ),
    ]
