# Generated by Django 2.2 on 2020-09-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('users', '0004_auto_20200930_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTFA',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token')),
                ('code', models.CharField(max_length=6)),
                ('gen_time', models.DateTimeField()),
            ],
            bases=('authtoken.token',),
        ),
    ]
