# Generated by Django 2.2 on 2020-10-02 11:58

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200930_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentfa',
            name='gen_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[users.validators.validate_phone_number]),
        ),
    ]
