# Generated by Django 2.2 on 2020-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201002_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='categoty',
            field=models.ManyToManyField(blank=True, null=True, to='categories.Category'),
        ),
    ]
