# Generated by Django 2.2 on 2020-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201002_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='categoty',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
