# Generated by Django 2.2 on 2020-10-16 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=225, verbose_name='موضوع')),
                ('content', models.TextField()),
                ('priorty', models.CharField(default='پایین', max_length=100, verbose_name='اولویت')),
                ('is_responded', models.BooleanField(default=False)),
                ('is_fake', models.BooleanField(blank=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_producer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
