# Generated by Django 2.2 on 2020-10-07 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('about_us_content', models.TextField(verbose_name='درباره ما')),
                ('about_damir_content', models.TextField(verbose_name='درباره دمیر')),
                ('buy_from_damir', models.TextField(verbose_name='خرید از دمیر')),
                ('sell_in_damir', models.TextField(verbose_name='فروش در دمیر')),
                ('terms_and_conditions', models.TextField(verbose_name='قوانین و مقررات')),
                ('privacy_and_policy', models.TextField(verbose_name='شرایط خصوصی')),
                ('sliders', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider_5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10240132, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTellerEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
