# Generated by Django 2.2 on 2020-09-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('about_us_content', models.TextField(verbose_name='درباره ما')),
                ('about_damir_content', models.TextField(verbose_name='درباره دمیر')),
                ('buy_from_damir', models.TextField(verbose_name='خرید از دمیر')),
                ('sell_in_damir', models.TextField(verbose_name='فروش در دمیر')),
                ('terms_and_conditions', models.TextField(verbose_name='قوانین و مقررات')),
                ('privacy_and_policy', models.TextField(verbose_name='شرایط خصوصی')),
            ],
        ),
    ]
