# Generated by Django 2.2 on 2020-09-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='slider_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slider_3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slider_4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slider_5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sliders',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
