# Generated by Django 2.2 on 2020-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200917_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='slider_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='slider_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='slider_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='slider_5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sliders',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
