# Generated by Django 2.2 on 2020-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='sharingpack'),
            preserve_default=False,
        ),
    ]
