# Generated by Django 2.2 on 2020-10-19 10:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='image_alt', max_length=600, verbose_name='seo image alternatinve'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(auto_now=True, verbose_name='تاریخ ثبت پست'),
        ),
    ]
