# Generated by Django 2.2 on 2020-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200922_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avg_read',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
