# Generated by Django 2.2 on 2020-09-24 07:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_post',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='I get those goosebumps everytime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='seo_post',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='I get thos goosebumps everytime'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FAQMainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2048)),
                ('text', models.TextField()),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.MainCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2048)),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
    ]
