# Generated by Django 2.2 on 2020-10-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_mothercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='mother_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.MotherCategory'),
            preserve_default=False,
        ),
    ]
