# Generated by Django 2.2 on 2020-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_maincategory_mother_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='model',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
