# Generated by Django 2.2 on 2020-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniorder',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
