# Generated by Django 2.2 on 2020-10-03 06:13

from django.db import migrations, models
import website.utils


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniorder',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[website.utils.validate_phone_number]),
        ),
    ]
