# Generated by Django 2.2 on 2020-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20201003_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniorder',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
