# Generated by Django 2.2 on 2020-10-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20201007_1338'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='selectable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.Variation'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='yes_or_no',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
