# Generated by Django 2.2 on 2020-09-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('categoryvariation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.CategoryVariation')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            bases=('categories.categoryvariation',),
        ),
    ]
