# Generated by Django 2.2 on 2020-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201007_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=164)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='label_try',
            field=models.ManyToManyField(to='products.Label'),
        ),
    ]
