# Generated by Django 2.2 on 2020-10-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slider_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_image6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_image7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_image8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider_image9',
        ),
    ]
