# Generated by Django 2.2 on 2020-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_price',
            field=models.FloatField(blank=True, null=True, verbose_name='بازه دوم قیمت'),
        ),
    ]
