# Generated by Django 2.2 on 2020-10-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201007_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
