# Generated by Django 2.2 on 2020-09-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_second_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_addded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
