# Generated by Django 2.2 on 2020-10-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201004_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaDetail',
        ),
    ]
