# Generated by Django 2.2 on 2020-10-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201016_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(default='image_alt', max_length=225),
            preserve_default=False,
        ),
    ]
