# Generated by Django 2.2 on 2020-10-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201018_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model': 'product'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
