# Generated by Django 2.2 on 2020-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201018_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
